### ISSUE TITLE
Current state of hQ (heterogeneous queuing)

### ISSUE THREAD

**Issue by VincentSC** [HSAFoundation/HSA-Drivers-Linux-AMD#21]
On the web I see a lot about hQ and hUMA, but I cannot really find it in the current implementations and descriptions. What are the words used now and what is the current status?

**Comment by gstoner** [comment]
These were AMD band names for 
- hQ  for User Mode Queues and AQL.   
hUMA - Heterogeneous Unified Memory which is Fine Grained Shared Virtual memory
