### ISSUE TITLE
after installing this am haveing some very bad audio issue 

### ISSUE THREAD

**Issue by Rajatkrghosh** [HSAFoundation/HSA-Drivers-Linux-AMD#23]
am having a hp laptop which has a currizo A10-8700p and R7-m360 with B&o sound speaker using ubuntu 16-04 after install this am having a very bad noise occour from my speaker

**Comment by gstoner** [comment]
These drivers have been superseded by ROCm Platform now hosted at Radeon Open Compute GitHub Repo https://github.com/RadeonOpenCompute

To install the new driver follow the instructions at https://radeonopencompute.github.io/install.html

If you want to find out more about ROCm platform and how it uses HSA Technologies you can goto https://radeonopencompute.github.io

**Comment by Rajatkrghosh** [comment]
also try this new one on ubuntu 160.4.1 but after reboot black screen
appearing
