### ISSUE TITLE
Split out HSA KMT

### ISSUE THREAD

**Issue by devurandom** [HSAFoundation/HSA-Drivers-Linux-AMD#24]
I am trying to build the [HSA runtime](https://github.com/HSAFoundation/HSA-Runtime-Reference-Source), for which I need HSA KMT (see the first comment in core/CMakeLists.txt there). I am pointed to this repository to get the sources, which I just finished cloning - a 1.2GiB download to get about 220KiB of HSA KMT sources... This is ridiculous...

To lower the adoption barriers, I suggest to split out the HSA KMT sources into a separate repository (and also version tag it).

**Comment by gstoner** [comment]
This source was  HSA 1.0  Reference Code,  AMD Donated to HSA Foundation a starting point help expidite has support on there hardware.     For AMD Systems we are only officially supporting ROCm ROCr Runtime, ROCt Thunk layer, ROCk Kernel driver.

Greg
On Aug 20, 2016, at 3:01 AM, Dennis Schridde <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to build the HSA runtime<https://github.com/HSAFoundation/HSA-Runtime-Reference-Source>, for which I need HSA KMT (see the first comment in core/CMakeLists.txt there). I am pointed to this repository to get the sources, which I just finished cloning - a 1.2GiB download to get about 220KiB of HSA KMT sources... This is ridiculous...

To lower the adoption barriers, I suggest to split out the HSA KMT sources into a separate repository (and also version tag it).

**Comment by devurandom** [comment]
Could this you make it clear in the readme? And point to the gpuopen website for the current AMD code?
